### ISSUE TITLE
How to append output to daily file?

### ISSUE THREAD

**Issue by yapsr** [pvachon/gm1356#1]
I am trying to log all measurements to a log file, preferably named like "/var/log/gm1356/20220613.txt"

Using the README file, I have managed to compile, run splread as a service on a Debian/Ubuntu system.

However, how do I send the output of this service splread to a local log file?
Can I use the created socket for this? Or should I change the service configuration to append all data to a log file?
I would really appreciate a simple step by step explanation how to do this, as my Linux skills are a bit limited.

Thank you,
Yaspr

**Comment by yapsr** [comment]
I guess I've found the answer to my own question here: https://stackoverflow.com/questions/37585758/how-to-redirect-output-of-systemd-service-to-a-file

**Comment by Potat0x** [comment]
Hi, if you need store measurements maybe it will be helpful https://github.com/Potat0x/GM1356-Sound-level-monitoring
